# Generated by Django 5.0.1 on 2024-01-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('Book_name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('ISBN', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=30)),
                ('quantity', models.CharField(max_length=100)),
            ],
        ),
    ]
